### ISSUE TITLE
// minimal example  #include <SDL3/SDL.h> #include <SDL3_mixer/SDL_mixer.h> #include <stdio.h>  int main(){     SDL_Init(SDL_INIT_AUDIO);      if(Mix_Init(MIX_INIT_OGG) <= 0)     {         printf("fail to init : %s", SDL_GetError());         return -1;     }      if(!Mix_OpenAudio(0, nullptr))     {         printf("fail to open");         return -1;     }      Mix_AllocateChannels(100);      Mix_Volume(-1, MIX_MAX_VOLUME);  	Mix_Chunk* chunk = Mix_LoadWAV("bounce.wav"); 	if(!chunk){ 		printf("failed to load chunk\n"); 		return -1; 	}  	int channel = Mix_PlayChannel(-1, chunk, 0); 	Mix_SetPosition(channel, 0, 0);  	SDL_Delay(2000);  	channel = Mix_PlayChannel(-1, chunk, 0); 	Mix_SetPosition(channel, 90, 0);  	SDL_Delay(2000);  	channel = Mix_PlayChannel(-1, chunk, 0); 	Mix_SetPosition(channel, 180, 0);  	SDL_Delay(2000);  	channel = Mix_PlayChannel(-1, chunk, 0); 	Mix_SetPosition(channel, 270, 0); // plays at the right speaker  	SDL_Delay(2000); }

### ISSUE THREAD

**Issue by Stauley** [libsdl-org/SDL_mixer#647] opened 2024-11-24 18:13 UTC
// minimal example

#include <SDL3/SDL.h>
#include <SDL3_mixer/SDL_mixer.h>
#include <stdio.h>

int main(){
    SDL_Init(SDL_INIT_AUDIO);

    if(Mix_Init(MIX_INIT_OGG) <= 0)
    {
        printf("fail to init : %s", SDL_GetError());
        return -1;
    }

    if(!Mix_OpenAudio(0, nullptr))
    {
        printf("fail to open");
        return -1;
    }

    Mix_AllocateChannels(100);

    Mix_Volume(-1, MIX_MAX_VOLUME);

	Mix_Chunk* chunk = Mix_LoadWAV("bounce.wav");
	if(!chunk){
		printf("failed to load chunk\n");
		return -1;
	}

	int channel = Mix_PlayChannel(-1, chunk, 0);
	Mix_SetPosition(channel, 0, 0);

	SDL_Delay(2000);

	channel = Mix_PlayChannel(-1, chunk, 0);
	Mix_SetPosition(channel, 90, 0);

	SDL_Delay(2000);

	channel = Mix_PlayChannel(-1, chunk, 0);
	Mix_SetPosition(channel, 180, 0);

	SDL_Delay(2000);

	channel = Mix_PlayChannel(-1, chunk, 0);
	Mix_SetPosition(channel, 270, 0); // plays at the right speaker

	SDL_Delay(2000);
}

**Comment by failedev17** [comment] 2024-11-24 18:18
What's this?

**Comment by sezero** [comment] 2024-11-24 18:27
Duplicate of https://github.com/libsdl-org/SDL_mixer/issues/646

**Closed by sezero** 2024-11-24 18:27 UTC
